### PR TITLE
refactor(backends/chroma): coerce None metadatas to `{}` at backend boundary (closes #1020)

### LINKED ISSUE #1020: refactor: coerce None metadatas at ChromaDB backend boundary (supersedes per-site guards from #999, #1013)
## Context

Two PRs recently merged to guard against \`None\` metadata / document entries returned by ChromaDB \`query()\`:

- **#999** — guards in \`searcher.py\` (\`search\`, \`search_memories\`), \`miner.py\` (\`status\`), \`mcp_server.py\` (4 sites) + regression tests. Merged at \`1b89b49\`.
- **#1013** — guards in \`layers.py\` (\`Layer3.search\`, \`Layer3.search_raw\`). Merged at \`6426669\`.

Both fix real user-visible crashes (\`AttributeError: 'NoneType' object has no attribute 'get'\`) that hit frequently on chromadb 1.5.x via the queue-stall in #1006.

Combined, these introduce ~9 per-site \`meta = meta or {}\` / \`doc = doc or \"\"\` guards across 5 files. During review of #999, @jphein proposed centralizing the coercion at the adapter boundary:

> \"Whack-a-mole across 8 call sites suggests the cleaner fix probably lives one layer down — either:
> 1. \`_get_cached_metadata\` / \`_fetch_all_metadata\` (in \`mcp_server.py\`) strip \`None\` entries as they build the cache, OR
> 2. \`ChromaCollection.get()\` / \`ChromaCollection.query()\` in \`backends/chroma.py\` coerce \`None\` metadatas to \`{}\` at the adapter boundary.
>
> Option 2 is more general — every future call site would get the guard for free... Happy to convert this to the adapter-level fix if maintainers prefer.\"

This issue tracks the adapter-level consolidation jphein offered.

## Proposal

Normalize \`None\` → \`{}\` (for metadatas) and \`None\` → \`\"\"\` (for documents) inside \`mempalace/backends/chroma.py\`'s \`ChromaCollection.query()\` and \`.get()\` return paths. Every consumer inherits the guard; every per-site \`meta or {}\` / \`doc or \"\"\` guard introduced by #999 and #1013 gets deleted.

## Alignment with RFC 001

This fits RFC 001's direction of formalizing backend return shapes (typed \`QueryResult\` / \`GetResult\`, normalized at the boundary). Arguably the coercion belongs in whatever the RFC 001 cleanup PR lands — merge coordination needed.

## Scope

- [ ] Add \`None\` → \`{}\` / \`\"\"\` coercion in \`ChromaCollection.query()\` return path
- [ ] Same for \`.get()\` return path
- [ ] Regression test at the adapter level (one test covers all callers)
- [ ] Delete per-site guards added by #999 in \`searcher.py\`, \`miner.py\`, \`mcp_server.py\`
- [ ] Delete per-site guards added by #1013 in \`layers.py\`
- [ ] Keep the per-site regression tests from #999 — they still verify downstream behavior under the same input shape

## Non-goals

- Handling \`None\` \`distances\` — not observed in practice; separate issue if it surfaces
- Full RFC 001 typed-result migration — that's #743 / its cleanup PR

## Offer to @jphein

You raised this during #999 review and offered to convert. If you have bandwidth, happy to have you drive this one — your diagnosis is clearest on what the failure mode looks like. Alternatively, any contributor can grab it.

## Related

- #999, #1013 — the per-site fixes this would supersede
- #1006 — root cause (chromadb 1.5.x queue-stall)
- #743 — RFC 001 storage backend plugin spec (adjacent)
- #487 — Python 3.13+ Pydantic V1 root cause

### PR DESCRIPTION
**Pull request by jphein**
## Summary

Fixes #1020. Moves the `None`-metadata coercion out of per-read-site defensive guards (`meta = meta or {}` scattered across `searcher.py`, `layers.py`, `palace_graph.py`, `miner.py`, etc.) and into the single place the typed contract is produced: `ChromaCollection.query()` and `ChromaCollection.get()` in `backends/chroma.py`.

## Why

ChromaDB 1.5.x can return `None` inside the `metadatas` list even when the write stored a dict. Three prior PRs already responded to this:

- **#999** — guards in `searcher.py` (CLI + API + closet-boost), `miner.status()`, and 4 `mcp_server.py` handlers
- **#1013** — guard in `Layer3.search_raw()`
- Various other paths picked up the same defensive pattern organically

That scatter works but violates the typed contract `QueryResult` and `GetResult` declare: both advertise `metadatas: list[dict]`, never `list[Optional[dict]]`. Every call site that forgets the guard is a latent `AttributeError: 'NoneType' object has no attribute 'get'`.

A boundary coercion is the right architectural fix: one place to handle the backend's quirk, downstream code gets the shape its type annotations promise.

## What changed

- `mempalace/backends/chroma.py`: added inner-list None-coercion inside `ChromaCollection.query()` (alongside the existing `_none_list_to_empty` outer coercion) and inside `ChromaCollection.get()` (after the existing `{}`-padding step). The guarantee becomes: whenever `metadatas` is requested, every element is a dict — never `None`.
- `tests/test_backends.py`: +6 tests covering the shapes the production code actually sees.

## What did NOT change

- The existing per-site `meta = meta or {}` guards stay in place as defensive belt-and-suspenders. They're redundant after this coercion but removing them risks regressing any call path that bypasses the typed wrappers. A follow-up cleanup PR can remove them once we're confident nothing else reaches chromadb directly.
- No behavior change on the write side. Writes still get whatever metadata the caller provides; this PR is strictly read-side.
- No change to `QueryResult` / `GetResult` shape. Same fields, same types — just guaranteed honored at the boundary instead of honored-with-asterisks.

## Test plan

- [x] `pytest tests/test_backends.py` — **35 passed** (6 new, 29 existing)
- [x] `pytest tests/` full suite — **1072 passed, 106 deselected**
- [x] `ruff check` on modified files — clean
- [x] `ruff format --check` with pinned 0.4.10 — clean

New test cases specifically target:

| Test | Exercises |
|---|---|
| `test_chroma_collection_query_coerces_none_metadatas_to_empty_dict` | mixed None/dict in a single-query batch |
| `test_chroma_collection_query_coerces_all_none_inner_metadatas` | degenerate: every metadata is None |
| `test_chroma_collection_query_coerces_none_across_multiple_queries` | None dicts spread across two queries in one call |
| `test_chroma_collection_get_coerces_none_metadatas_to_empty_dict` | mixed None/dict on `get()` path |
| `test_chroma_collection_get_coerces_padding_remains_dict` | regression guard: short metas list → `{}` pads stay `{}` |
| `test_chroma_collection_get_without_metadatas_requested_stays_empty` | when metadatas not in `include=`, don't fabricate |

## Context

I'd committed to driving this on #1020 on 2026-04-18; #1021's merge this week cleared the blocker. @bensig — happy to split into two PRs (the coercion itself and a separate guard-removal follow-up) if you'd prefer landing them serially, but as written this PR keeps behavior strictly monotonic: everything that worked before still works, plus one class of latent None-metadata bugs can't fire anymore.

### CODE REVIEW

File: tests/test_backends.py [hunk 1]
```diff
@@ -127,6 +127,107 @@ def test_chroma_collection_rejects_unknown_where_operator():
...
+        "distances": [[0.1, 0.2, 0.3]],
+    }
+    collection = ChromaCollection(_FakeCollection(query_response=raw))
+
+    result = collection.query(query_texts=["q"])
+
+    assert result.metadatas == [[{"wing": "w1"}, {}, {"wing": "w3"}]]
+    # Ids/docs/distances unaffected — their inner None handling is already
+    # covered by the outer-list coercion.
+    assert result.ids == [["a", "b", "c"]]
```
[the remark this answers is not in the document]
Comment (jphein) [reply tests/test_backends.py:163]: Done in `bf91b27` — added `assert result.documents == [["da", "db", "dc"]]` so the comment's claim is actually pinned by the test. 12/12 backend tests pass.

**Comment by jphein** [comment]
Small, self-contained bug fix for #1020: coerce inner-list `None` metadatas to `{}` at the ChromaDB backend boundary so callers always receive `list[dict]` and downstream `meta.get(...)` can't crash on the ChromaDB 1.5.x shape. This is the boundary fix #1020 describes as superseding the per-site guards from #999/#1013. Backend-level regression tests cover the mixed/degenerate `None` shapes, and it merges clean on `develop`. Would appreciate a review when someone has a moment — happy to rebase if needed.
